site_name: Robo's Minimap
site_url: https://robocrafterlp.github.io/robo-minimap
repo_name: RobocrafterLP/robo-minimap
repo_url: https://github.com/robocrafterlp/robo-minimap

theme:
  icon:
    logo: material/map
  name: material
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: purple 

nav:
  - Home: index.md
  # - API: api.md
  # - Tutorial: tutorial/index.md
  # - Troubleshooting: troubleshooting/index.md
  # - DataStore Use: datause/index.md
  # - Developer Products: devproducts/index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences